NDefines.NAirGfx.AIRPLANES_ANIMATION_GLOBAL_SPEED_PER_GAMESPEED = { 0, 0.3 , 0.5 , 0.7, 0.9, 1.1 }
NDefines.NAirGfx.ROCKET_SPEED = 40
NDefines.NAirGfx.AIRPLANES_CURVE_MAX_EXTRAPOLATION = 60

NDefines.NAirGfx.BOMBERS_DIVISION_FACTOR = 30
NDefines.NAirGfx.MISSILES_DIVISION_FACTOR = 1
NDefines.NAirGfx.FIGHTERS_DIVISION_FACTOR = 30
NDefines.NAirGfx.SCOUT_PLANE_DIVISION_FACTOR = 30
NDefines.NAirGfx.TRANSPORT_DIVISION_FACTOR = 30
NDefines.NAirGfx.AIRPLANES_SCALE_MIN = 0.01

NDefines.NAirGfx.MAX_MISSILE_BOMBING_SCENARIOS = 500
NDefines.NAirGfx.MAX_PATROL_SCENARIOS = 10
NDefines.NAirGfx.MAX_BOMBING_SCENARIOS = 15
NDefines.NAirGfx.MAX_DOGFIGHTS_SCENARIOS = 6
NDefines.NAirGfx.MAX_TRANSPORT_SCENARIOS = 20
NDefines.NAirGfx.MAX_TRAINING_SCENARIOS = 10
NDefines.NAirGfx.MAX_SCOUT_SCENARIOS = 10