NDefines.ACCLIMATIZATION_IN_COMBAT_SPEED_FACTOR = 0.25
NDefines.ACCLIMATIZATION_SPEED_GAIN = 0.1
NDefines.ACCLIMATIZATION_LOSS_SPEED_FACTOR = 1.0
NDefines.NGraphics.WEATHER_DISTANCE_CUTOFF = 1200
NDefines.NGraphics.WEATHER_ZOOM_IN_CUTOFF = 1
NDefines.NGraphics.WEATHER_PLAYBACK_RATE = 0.25
NDefines.NGraphics.WEATHER_PLAYBACK_RATE_CUTOFF = 400
NDefines.NGraphics.WEATHER_PLAYBACK_RATE_LENGTH = 200
